using System;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Windows.Forms;
using Microsoft.Win32;
using Timer = System.Windows.Forms.Timer;

namespace LumiZoom
{
 static class Program { static System.Threading.Mutex instance; [STAThread] static void Main(){bool first;instance=new System.Threading.Mutex(true,@"Local\LumiZoom.SingleInstance",out first);if(!first)return;Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(true);Application.Run(new TrayContext());GC.KeepAlive(instance);} }
 sealed class TrayContext:ApplicationContext
 {
  const int ID=0x544C; const string AppVersion="1.0 RC2"; const string AppAuthor="Łukasz Kuczek"; const string ProjectUrl="https://github.com/lumizoom-project/LumiZoom"; const string ContactEmail="lumizoom.project@gmail.com"; readonly NotifyIcon tray; readonly MessageWindow window; readonly Timer timer; readonly ToolStripMenuItem toggleMenu; readonly ContextMenuStrip trayMenu;
  uint hotkeyModifiers,hotkeyKey;
  Form optionsForm;
  int zoom, speed, animationMs, fontSizeMode, themeMode, languageMode, highlightOpacity, highlightColorArgb; bool center, autostart, startZoomed, trayClick, emergencyEsc, applyZoomLive, cursorHighlight, enabled, animating; float level=1, fromLevel, toLevel; DateTime animationStart; double offsetX,offsetY; readonly CursorHalo halo;
  public TrayContext(){Load();window=new MessageWindow();window.HotkeyPressed+=Toggle;Native.MagInitialize();
   if(!Native.RegisterHotKey(window.Handle,ID,hotkeyModifiers,hotkeyKey))MessageBox.Show(L("Wybrany skrót jest zajęty."),"LumiZoom");
   trayMenu=new ContextMenuStrip();toggleMenu=new ToolStripMenuItem(L("Włącz / wyłącz")+"   "+HotkeyText(hotkeyModifiers,hotkeyKey),null,delegate{Toggle();});trayMenu.Items.Add(toggleMenu);trayMenu.Items.Add(L("Opcje..."),null,delegate{Options();});trayMenu.Items.Add(new ToolStripSeparator());trayMenu.Items.Add(L("Zamknij"),null,delegate{ExitApp();});ApplyMenuStyle();
   tray=new NotifyIcon{Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath),Text="LumiZoom — "+HotkeyText(hotkeyModifiers,hotkeyKey),ContextMenuStrip=trayMenu,Visible=true};tray.DoubleClick+=delegate{Toggle();};tray.MouseClick+=delegate(object sender,MouseEventArgs e){if(trayClick&&e.Button==MouseButtons.Left)Toggle();};
   timer=new Timer{Interval=16};timer.Tick+=delegate{Tick();};
   halo=new CursorHalo();
   if(startZoomed){var delayed=new Timer{Interval=400};delayed.Tick+=delegate{delayed.Stop();delayed.Dispose();Toggle();};delayed.Start();}
  }
  void Toggle(){enabled=!enabled;if(emergencyEsc){if(enabled)Native.RegisterHotKey(window.Handle,ID+1,0,0x1B);else Native.UnregisterHotKey(window.Handle,ID+1);}fromLevel=level;toLevel=enabled?zoom/100f:1f;animationStart=DateTime.UtcNow;animating=true;timer.Start();tray.Text=enabled?"LumiZoom — "+L("aktywny")+" "+zoom+"%":"LumiZoom — "+L("wyłączony");}
  void Tick(){
   if(animating){double t=animationMs<=0?1:(DateTime.UtcNow-animationStart).TotalMilliseconds/animationMs;if(t>=1){t=1;animating=false;} double eased=1-Math.Pow(1-t,3);level=(float)(fromLevel+(toLevel-fromLevel)*eased);}
   Native.POINT p;Native.GetCursorPos(out p);int w=Native.GetSystemMetrics(0),h=Native.GetSystemMetrics(1);int sw=(int)(w/level),sh=(int)(h/level);
   if(enabled&&cursorHighlight){halo.SetAppearance(Color.FromArgb(highlightColorArgb),highlightOpacity);halo.ShowAt(p.X,p.Y);}else halo.Hide();
   double tx=Math.Max(0,Math.Min(p.X-sw/2,w-sw)),ty=Math.Max(0,Math.Min(p.Y-sh/2,h-sh));double f=center?1:0.05+speed*0.045;offsetX+=(tx-offsetX)*f;offsetY+=(ty-offsetY)*f;
   int ox=(int)Math.Round(offsetX),oy=(int)Math.Round(offsetY);Native.MagSetFullscreenTransform(level,ox,oy);
   if(level>1.001f){Native.RECT src=new Native.RECT{Left=ox,Top=oy,Right=ox+sw,Bottom=oy+sh};Native.RECT dst=new Native.RECT{Left=0,Top=0,Right=w,Bottom=h};if(!Native.MagSetInputTransform(true,ref src,ref dst)){tray.Text="LumiZoom — brak UIAccess";}}
   else {Native.RECT a=new Native.RECT(),b=new Native.RECT();Native.MagSetInputTransform(false,ref a,ref b);if(!enabled&&!animating)timer.Stop();}
  }
  void Options(){if(optionsForm!=null&&!optionsForm.IsDisposed){optionsForm.Activate();optionsForm.BringToFront();return;}int oldZoom=zoom,oldSpeed=speed,oldAnimation=animationMs,oldHighlightOpacity=highlightOpacity,oldHighlightColor=highlightColorArgb,oldLanguage=languageMode;bool oldCenter=center,oldApplyLive=applyZoomLive,oldCursorHighlight=cursorHighlight;float fs=UiFontSize();int extra=fontSizeMode*35;using(var f=new Form{Text="LumiZoom — ustawienia",ClientSize=new Size(560+extra,650+fontSizeMode*35),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,StartPosition=FormStartPosition.CenterScreen,Font=new Font("Segoe UI",fs),AutoScaleMode=AutoScaleMode.Dpi,Opacity=0})using(var z=new NumericUpDown())using(var zoomSlider=new TrackBar())using(var s=new NumericUpDown())using(var a=new NumericUpDown())using(var c=new CheckBox())using(var live=new CheckBox())using(var highlight=new CheckBox())using(var opacity=new TrackBar())using(var run=new CheckBox())using(var start=new CheckBox())using(var click=new CheckBox())using(var esc=new CheckBox())using(var shortcut=new TextBox())using(var fontChoice=new ComboBox())using(var themeChoice=new ComboBox())using(var languageChoice=new LanguageCombo()){
   optionsForm=f;f.FormClosed+=delegate{if(Object.ReferenceEquals(optionsForm,f))optionsForm=null;};
   f.Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);var title=new BrandHeader{Tag="brandHeader",Left=20,Top=7,Width=430,Height=52,Font=new Font("Atkinson Hyperlegible",fs+8,FontStyle.Bold)};f.Controls.Add(title);
   var tabs=new StyledTabControl{Left=20,Top=62,Width=f.ClientSize.Width-40,Height=f.ClientSize.Height-155,Font=new Font("Segoe UI Semibold",fs)};var view=new TabPage("Główna"){Padding=new Padding(20)};var cursorPage=new TabPage("Kursor"){Padding=new Padding(20)};var app=new TabPage("Program"){Padding=new Padding(20)};var appearance=new TabPage("Wygląd"){Padding=new Padding(20)};var aboutPage=new TabPage("O LumiZoom"){Padding=new Padding(20)};tabs.TabPages.Add(view);tabs.TabPages.Add(cursorPage);tabs.TabPages.Add(app);tabs.TabPages.Add(appearance);tabs.TabPages.Add(aboutPage);tabs.UpdateTabWidths();f.Controls.Add(tabs);
   var zoomLabel=new Label{Text="Poziom powiększenia",Left=18,Top=20,AutoSize=false,Height=34};view.Controls.Add(zoomLabel);z.SetBounds(360,15,100,32);z.Minimum=100;z.Maximum=1000;z.Increment=25;z.Value=zoom;view.Controls.Add(z);var zoomUnit=new Label{Text="%",Left=468,Top=20,AutoSize=true};view.Controls.Add(zoomUnit);
   zoomSlider.SetBounds(18,52,490,45);zoomSlider.Minimum=100;zoomSlider.Maximum=1000;zoomSlider.TickFrequency=100;zoomSlider.SmallChange=25;zoomSlider.LargeChange=50;zoomSlider.Value=zoom;view.Controls.Add(zoomSlider);
   live.Text="Zastosuj zmiany powiększenia na żywo";live.SetBounds(18,100,520,32);live.AutoSize=true;live.Checked=applyZoomLive;view.Controls.Add(live);
   view.Controls.Add(new Label{Text="Po zaznaczeniu zmiany suwaka i ustawień są od razu widoczne na ekranie.",Left=42,Top=136,Width=540,Height=72,ForeColor=Color.Gray});
   var animationLabel=new Label{Text="Czas animacji",Left=18,Top=218,AutoSize=false,Height=34};view.Controls.Add(animationLabel);a.SetBounds(360,212,100,32);a.Minimum=0;a.Maximum=2000;a.Increment=100;a.Value=animationMs;view.Controls.Add(a);var animationUnit=new Label{Text="ms",Left=468,Top=218,AutoSize=true};view.Controls.Add(animationUnit);
   c.Text="Utrzymuj kursor na środku ekranu";c.SetBounds(18,258,580,34);c.AutoSize=true;c.Checked=center;view.Controls.Add(c);
   var speedLabel=new Label{Text="Szybkość płynnego śledzenia",Left=18,Top=306,AutoSize=false,Height=34};view.Controls.Add(speedLabel);s.SetBounds(360,300,80,32);s.Minimum=1;s.Maximum=10;s.Value=speed;view.Controls.Add(s);var speedUnit=new Label{Text="1–10",Left=448,Top=306,AutoSize=true};view.Controls.Add(speedUnit);
   highlight.Text="Podświetlaj położenie kursora";highlight.SetBounds(18,25,520,34);highlight.AutoSize=true;highlight.Checked=cursorHighlight;cursorPage.Controls.Add(highlight);
   cursorPage.Controls.Add(new Label{Text="Wybrany kolor",Left=18,Top=78,AutoSize=true});var colorSwatch=new Panel{Tag="colorSwatch",Left=175,Top=72,Width=62,Height=38,BackColor=Color.FromArgb(highlightColorArgb),BorderStyle=BorderStyle.FixedSingle};cursorPage.Controls.Add(colorSwatch);
   Color[] presetColors={Color.Yellow,Color.Red,Color.Lime,Color.Cyan,Color.Magenta,Color.White};var presetButtons=new Button[presetColors.Length];for(int pi=0;pi<presetColors.Length;pi++){int index=pi;presetButtons[pi]=new Button{Left=18+pi*48,Top=125,Width=38,Height=38,BackColor=presetColors[pi],FlatStyle=FlatStyle.Flat,Tag="colorPreset"};presetButtons[pi].FlatAppearance.BorderColor=Color.Gray;presetButtons[pi].Click+=delegate{highlightColorArgb=presetColors[index].ToArgb();colorSwatch.BackColor=presetColors[index];};cursorPage.Controls.Add(presetButtons[pi]);}
   var colorButton=new Button{Text="Inny kolor…",Left=320,Top=123,Width=165,Height=42,FlatStyle=FlatStyle.System};cursorPage.Controls.Add(colorButton);
   cursorPage.Controls.Add(new Label{Text="Przezroczystość podświetlenia",Left=18,Top=190,AutoSize=true});opacity.SetBounds(18,225,480,50);opacity.Minimum=10;opacity.Maximum=100;opacity.TickFrequency=10;opacity.Value=highlightOpacity;cursorPage.Controls.Add(opacity);var opacityValue=new Label{Text=highlightOpacity+"%",Left=510,Top=230,AutoSize=true};cursorPage.Controls.Add(opacityValue);
   run.Text="Uruchamiaj razem z Windows";run.SetBounds(18,25,560,34);run.AutoSize=true;run.Checked=autostart;app.Controls.Add(run);
   start.Text="Włącz powiększenie po uruchomieniu";start.SetBounds(18,65,560,34);start.AutoSize=true;start.Checked=startZoomed;app.Controls.Add(start);
   click.Text="Lewy klik ikony w zasobniku przełącza zoom";click.SetBounds(18,105,590,34);click.AutoSize=true;click.Checked=trayClick;app.Controls.Add(click);
   esc.Text="Awaryjne wyłączenie klawiszem Esc";esc.SetBounds(18,145,560,34);esc.AutoSize=true;esc.Checked=emergencyEsc;app.Controls.Add(esc);
   var about=new GroupBox{Text="O LumiZoom",Left=18,Top=18,Width=520,Height=205,Padding=new Padding(16,30,16,10),Tag="aboutBox"};var aboutVersion=new Label{Text="Wersja: "+AppVersion,Left=18,Top=34,AutoSize=true,Tag="aboutText"};var aboutAuthor=new Label{Text="Autor: "+AppAuthor,Left=18,Top=66,AutoSize=true,Tag="aboutText"};var aboutPurpose=new Label{Text="Bezpłatna lupa ekranowa dla osób niedowidzących.",Left=18,Top=98,AutoSize=true,Tag="aboutText"};var projectLabel=new Label{Text="Strona projektu:",Left=18,Top=130,AutoSize=true,Tag="aboutText"};var projectLink=new LinkLabel{Text=ProjectUrl,Left=145,Top=130,AutoSize=true,Tag="projectLink"};var contactLabel=new Label{Text="Kontakt:",Left=18,Top=162,AutoSize=true,Tag="aboutText"};var contactLink=new LinkLabel{Text=ContactEmail,Left=100,Top=162,AutoSize=true,Tag="projectLink"};projectLink.LinkClicked+=delegate{try{System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(ProjectUrl){UseShellExecute=true});}catch{};};contactLink.LinkClicked+=delegate{try{System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo("mailto:"+ContactEmail){UseShellExecute=true});}catch{};};about.Controls.AddRange(new Control[]{aboutVersion,aboutAuthor,aboutPurpose,projectLabel,projectLink,contactLabel,contactLink});aboutPage.Controls.Add(about);
   var shortcutLabel=new Label{Text="Skrót włącz/wyłącz",Left=18,Top=354,AutoSize=false,Height=36};view.Controls.Add(shortcutLabel);shortcut.SetBounds(300,348,300,38);shortcut.Text=HotkeyText(hotkeyModifiers,hotkeyKey);uint newMods=hotkeyModifiers,newKey=hotkeyKey;bool captured=false;string oldShortcut=shortcut.Text;
   shortcut.Enter+=delegate{captured=false;shortcut.Text="";Native.SendMessage(shortcut.Handle,0x1501,new IntPtr(1),"Naciśnij nowy skrót…");shortcut.Select(0,0);};
   shortcut.KeyDown+=delegate(object sender,KeyEventArgs e){if(e.KeyCode==Keys.Escape||e.KeyCode==Keys.Back||e.KeyCode==Keys.Delete){captured=false;shortcut.Text=oldShortcut;shortcut.ForeColor=ThemeText();f.ActiveControl=null;e.SuppressKeyPress=true;return;}uint m=(e.Control?2u:0u)|(e.Alt?1u:0u)|(e.Shift?4u:0u)|((e.KeyCode==Keys.LWin||e.KeyCode==Keys.RWin)?8u:0u);if(e.KeyCode!=Keys.ControlKey&&e.KeyCode!=Keys.Menu&&e.KeyCode!=Keys.ShiftKey&&e.KeyCode!=Keys.LWin&&e.KeyCode!=Keys.RWin){newMods=m;newKey=(uint)e.KeyCode;shortcut.Text=HotkeyText(newMods,newKey);shortcut.ForeColor=ThemeText();captured=true;shortcut.Select(shortcut.TextLength,0);}e.SuppressKeyPress=true;};
   shortcut.Leave+=delegate{Native.SendMessage(shortcut.Handle,0x1501,IntPtr.Zero,"");if(!captured){shortcut.Text=oldShortcut;shortcut.ForeColor=ThemeText();}};view.Controls.Add(shortcut);
   var languageLabel=new Label{Text="Język aplikacji",Left=18,Top=410,AutoSize=false,Height=40};view.Controls.Add(languageLabel);languageChoice.SetBounds(215,400,320,44);languageChoice.DropDownStyle=ComboBoxStyle.DropDownList;languageChoice.Font=new Font("Segoe UI",fs);languageChoice.Items.AddRange(Localizer.LanguageNames);languageChoice.SelectedIndex=Math.Max(0,Math.Min(Localizer.LanguageNames.Length-1,languageMode));view.Controls.Add(languageChoice);
   appearance.Controls.Add(new Label{Text="Rozmiar interfejsu",Left=18,Top=18,Width=220});fontChoice.Items.AddRange(new object[]{"Mały","Średni","Duży"});fontChoice.SelectedIndex=fontSizeMode;
   var sizeSmall=new Button{Text="A\r\nMały",Tag="sizeIcon",Font=new Font("Segoe UI Semibold",10),Left=18,Top=52,Width=120,Height=72,FlatStyle=FlatStyle.Flat};var sizeMedium=new Button{Text="A\r\nŚredni",Tag="sizeIcon",Font=new Font("Segoe UI Semibold",14),Left=150,Top=52,Width=120,Height=72,FlatStyle=FlatStyle.Flat};var sizeLarge=new Button{Text="A\r\nDuży",Tag="sizeIcon",Font=new Font("Segoe UI Semibold",18),Left=282,Top=52,Width=120,Height=72,FlatStyle=FlatStyle.Flat};appearance.Controls.AddRange(new Control[]{sizeSmall,sizeMedium,sizeLarge});
   appearance.Controls.Add(new Label{Text="Motyw kolorystyczny",Left=18,Top=142,Width=220});themeChoice.Items.AddRange(new object[]{"System","Jasny","Ciemny"});themeChoice.SelectedIndex=themeMode;
   var themeSystem=new Button{Text="◐\r\nSystem",Tag="themeIcon",Font=new Font("Segoe UI Symbol",12),Left=18,Top=176,Width=120,Height=72,FlatStyle=FlatStyle.Flat};var themeLight=new Button{Text="☀\r\nJasny",Tag="themeIcon",Font=new Font("Segoe UI Symbol",12),Left=150,Top=176,Width=120,Height=72,FlatStyle=FlatStyle.Flat};var themeDark=new Button{Text="●\r\nCiemny",Tag="themeIcon",Font=new Font("Segoe UI Symbol",12),Left=282,Top=176,Width=120,Height=72,FlatStyle=FlatStyle.Flat};appearance.Controls.AddRange(new Control[]{themeSystem,themeLight,themeDark});
   appearance.Controls.Add(new Label{Text="Podgląd zmienia się natychmiast.",Left=18,Top=260,Width=420,Height=35,ForeColor=Color.Gray});
   var defaults=new Button{Text="Przywróć domyślne",Left=20,Top=f.ClientSize.Height-58,Width=190,Height=38};defaults.Click+=delegate{z.Value=200;a.Value=300;s.Value=6;c.Checked=true;run.Checked=true;start.Checked=false;click.Checked=false;esc.Checked=true;newMods=7;newKey=0x39;captured=true;shortcut.ForeColor=ThemeText();shortcut.Text=HotkeyText(newMods,newKey);fontChoice.SelectedIndex=1;themeChoice.SelectedIndex=0;languageChoice.SelectedIndex=Localizer.DefaultLanguage();};f.Controls.Add(defaults);
   var cancel=new Button{Text="Wyjdź",Tag="secondaryAction",Left=f.ClientSize.Width-350,Top=f.ClientSize.Height-58,Width=130,Height=38,DialogResult=DialogResult.Cancel};var ok=new Button{Text="Zapisz i wyjdź",Tag="primaryAction",Left=f.ClientSize.Width-210,Top=f.ClientSize.Height-58,Width=190,Height=38,DialogResult=DialogResult.OK};f.Controls.Add(cancel);f.Controls.Add(ok);f.AcceptButton=ok;f.CancelButton=cancel;Action restoreShortcut=delegate{captured=false;newMods=hotkeyModifiers;newKey=hotkeyKey;Native.SendMessage(shortcut.Handle,0x1501,IntPtr.Zero,"");shortcut.Text=oldShortcut;shortcut.ForeColor=ThemeText();};WireOutsideClick(f,shortcut,ok,restoreShortcut);ApplyTheme(f);
   bool syncing=false;Action applyMagnification=delegate{zoom=(int)z.Value;animationMs=(int)a.Value;speed=(int)s.Value;center=c.Checked;applyZoomLive=live.Checked;if(enabled&&applyZoomLive){fromLevel=level;toLevel=zoom/100f;animationStart=DateTime.UtcNow;animating=true;timer.Start();}};z.ValueChanged+=delegate{if(!syncing){syncing=true;zoomSlider.Value=(int)z.Value;syncing=false;applyMagnification();}};zoomSlider.Scroll+=delegate{if(!syncing){syncing=true;z.Value=zoomSlider.Value;syncing=false;applyMagnification();}};a.ValueChanged+=delegate{applyMagnification();};s.ValueChanged+=delegate{applyMagnification();};c.CheckedChanged+=delegate{applyMagnification();};live.CheckedChanged+=delegate{applyMagnification();};
   Action applyCursor=delegate{cursorHighlight=highlight.Checked;highlightOpacity=opacity.Value;opacityValue.Text=highlightOpacity+"%";if(!cursorHighlight)halo.Hide();};highlight.CheckedChanged+=delegate{applyCursor();};opacity.Scroll+=delegate{applyCursor();};colorButton.Click+=delegate{using(var d=new ColorDialog()){d.Color=Color.FromArgb(highlightColorArgb);d.FullOpen=true;if(d.ShowDialog()==DialogResult.OK){highlightColorArgb=d.Color.ToArgb();colorSwatch.BackColor=d.Color;applyCursor();}}};
   int originalFontMode=fontSizeMode,originalThemeMode=themeMode;Action preview=delegate{
    fontSizeMode=fontChoice.SelectedIndex;themeMode=themeChoice.SelectedIndex;languageMode=languageChoice.SelectedIndex;float pf=UiFontSize();int pe=fontSizeMode*55;
    f.ClientSize=new Size(560+pe,650+fontSizeMode*55);ApplyFont(f,pf);languageChoice.Font=new Font("Segoe UI",pf);title.Font=new Font("Atkinson Hyperlegible",pf+8,FontStyle.Bold);title.Width=Math.Min(520,f.ClientSize.Width-40);title.Height=52;
    tabs.Font=new Font("Segoe UI Semibold",pf);tabs.Width=f.ClientSize.Width-40;tabs.Height=f.ClientSize.Height-155;tabs.Dark=IsDark();tabs.UpdateTabWidths();zoomSlider.Width=tabs.ClientSize.Width-55;opacity.Width=tabs.ClientSize.Width-130;opacityValue.Left=tabs.ClientSize.Width-90;
    int valueX=Math.Max(360,tabs.ClientSize.Width-150);z.Left=valueX;a.Left=valueX;s.Left=valueX;zoomLabel.Width=valueX-36;animationLabel.Width=valueX-36;speedLabel.Width=valueX-36;zoomUnit.Left=valueX+108;animationUnit.Left=valueX+108;speedUnit.Left=valueX+88;about.Width=tabs.ClientSize.Width-36;
    int fieldX=Math.Max(300,tabs.ClientSize.Width-325);shortcut.Left=fieldX;shortcut.Width=tabs.ClientSize.Width-fieldX-20;shortcutLabel.Width=fieldX-36;languageChoice.Left=Math.Max(215,fieldX-45);languageChoice.Width=tabs.ClientSize.Width-languageChoice.Left-20;languageLabel.Width=languageChoice.Left-36;
    defaults.Top=f.ClientSize.Height-58;cancel.Left=f.ClientSize.Width-350;cancel.Top=f.ClientSize.Height-58;ok.Left=f.ClientSize.Width-210;ok.Top=f.ClientSize.Height-58;
    Localizer.Apply(f,languageMode);about.Text=L("O LumiZoom");aboutVersion.Text=L("Wersja")+": "+AppVersion;aboutAuthor.Text=L("Autor")+": "+AppAuthor;aboutPurpose.Text=L("Bezpłatna lupa ekranowa dla osób niedowidzących.");projectLabel.Text=L("Strona projektu")+":";contactLabel.Text=L("Kontakt")+":";projectLink.Left=projectLabel.Left+projectLabel.PreferredWidth+12;contactLink.Left=contactLabel.Left+contactLabel.PreferredWidth+12;ApplyTheme(f);colorSwatch.BackColor=Color.FromArgb(highlightColorArgb);for(int pc=0;pc<presetButtons.Length;pc++)presetButtons[pc].BackColor=presetColors[pc];Button[] sb={sizeSmall,sizeMedium,sizeLarge},tb={themeSystem,themeLight,themeDark};for(int i=0;i<3;i++){sb[i].FlatStyle=FlatStyle.Flat;tb[i].FlatStyle=FlatStyle.Flat;sb[i].FlatAppearance.BorderSize=i==fontSizeMode?3:1;tb[i].FlatAppearance.BorderSize=i==themeMode?3:1;sb[i].FlatAppearance.BorderColor=i==fontSizeMode?Color.FromArgb(31,181,224):Color.FromArgb(105,126,151);tb[i].FlatAppearance.BorderColor=i==themeMode?Color.FromArgb(31,181,224):Color.FromArgb(105,126,151);}sizeSmall.Font=new Font("Segoe UI Semibold",10);sizeMedium.Font=new Font("Segoe UI Semibold",14);sizeLarge.Font=new Font("Segoe UI Semibold",18);themeSystem.Font=themeLight.Font=themeDark.Font=new Font("Segoe UI Symbol",12);title.Invalidate();
   };fontChoice.SelectedIndexChanged+=delegate{preview();};themeChoice.SelectedIndexChanged+=delegate{preview();};languageChoice.SelectedIndexChanged+=delegate{preview();};sizeSmall.Click+=delegate{fontChoice.SelectedIndex=0;};sizeMedium.Click+=delegate{fontChoice.SelectedIndex=1;};sizeLarge.Click+=delegate{fontChoice.SelectedIndex=2;};themeSystem.Click+=delegate{themeChoice.SelectedIndex=0;};themeLight.Click+=delegate{themeChoice.SelectedIndex=1;};themeDark.Click+=delegate{themeChoice.SelectedIndex=2;};preview();
   var fade=new Timer{Interval=16};fade.Tick+=delegate{f.Opacity=Math.Min(1,f.Opacity+0.12);if(f.Opacity>=1){fade.Stop();fade.Dispose();}};f.Shown+=delegate{fade.Start();};
   if(f.ShowDialog()==DialogResult.OK){if(captured){Native.UnregisterHotKey(window.Handle,ID);if(!Native.RegisterHotKey(window.Handle,ID,newMods,newKey)){Native.RegisterHotKey(window.Handle,ID,hotkeyModifiers,hotkeyKey);MessageBox.Show(L("Ten skrót jest już używany. Zachowano poprzedni."),"LumiZoom");}else{hotkeyModifiers=newMods;hotkeyKey=newKey;}}applyMagnification();applyCursor();autostart=run.Checked;startZoomed=start.Checked;trayClick=click.Checked;emergencyEsc=esc.Checked;fontSizeMode=fontChoice.SelectedIndex;themeMode=themeChoice.SelectedIndex;languageMode=languageChoice.SelectedIndex;toggleMenu.Text=L("Włącz / wyłącz")+"   "+HotkeyText(hotkeyModifiers,hotkeyKey);trayMenu.Items[1].Text=L("Opcje...");trayMenu.Items[3].Text=L("Zamknij");ApplyMenuStyle();Save();}else{zoom=oldZoom;speed=oldSpeed;animationMs=oldAnimation;center=oldCenter;applyZoomLive=oldApplyLive;cursorHighlight=oldCursorHighlight;highlightOpacity=oldHighlightOpacity;highlightColorArgb=oldHighlightColor;fontSizeMode=originalFontMode;themeMode=originalThemeMode;languageMode=oldLanguage;if(enabled){fromLevel=level;toLevel=zoom/100f;animationStart=DateTime.UtcNow;animating=true;timer.Start();}if(!cursorHighlight)halo.Hide();ApplyMenuStyle();} }
  }
  static string HotkeyText(uint mods,uint key){string t="";if((mods&2)!=0)t+="Ctrl + ";if((mods&1)!=0)t+="Alt + ";if((mods&4)!=0)t+="Shift + ";if((mods&8)!=0)t+="Win + ";string k=((Keys)key).ToString();if(key>=0x30&&key<=0x39)k=((char)key).ToString();return t+k;}
  string L(string polish){return Localizer.Get(polish,languageMode);}
  float UiFontSize(){return fontSizeMode==0?10f:fontSizeMode==2?18f:14f;}
  bool IsDark(){if(themeMode==2)return true;if(themeMode==1)return false;using(var k=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"))return k!=null&&Convert.ToInt32(k.GetValue("AppsUseLightTheme",1))==0;}
  Color ThemeText(){return IsDark()?Color.FromArgb(244,249,255):Color.FromArgb(15,39,70);}
  void ApplyFont(Control root,float size){if(!object.Equals(root.Tag,"sizeIcon")&&!object.Equals(root.Tag,"brandHeader"))root.Font=new Font("Segoe UI",size);foreach(Control x in root.Controls)ApplyFont(x,size);}
  void WireOutsideClick(Control root,Control field,Control save,Action restore){foreach(Control x in root.Controls){if(x!=field&&x!=save)x.MouseDown+=delegate{if(field.Focused)restore();};WireOutsideClick(x,field,save,restore);}}
  void ApplyTheme(Control root){bool dark=IsDark();Color bg=dark?Color.FromArgb(14,27,46):Color.FromArgb(243,248,252),panel=dark?Color.FromArgb(23,43,67):Color.White,field=dark?Color.FromArgb(31,55,82):Color.FromArgb(250,253,255),fg=ThemeText(),accent=Color.FromArgb(31,181,224),navy=Color.FromArgb(15,39,70);if(root is StyledTabControl){((StyledTabControl)root).Dark=dark;((StyledTabControl)root).Invalidate();}if(root is BrandHeader){((BrandHeader)root).Dark=dark;((BrandHeader)root).Invalidate();}if(!object.Equals(root.Tag,"colorPreset")&&!object.Equals(root.Tag,"colorSwatch")&&!object.Equals(root.Tag,"brandHeader")&&!object.Equals(root.Tag,"primaryAction")&&!object.Equals(root.Tag,"secondaryAction")){root.BackColor=bg;root.ForeColor=fg;}foreach(Control x in root.Controls){x.ForeColor=fg;if(x is LinkLabel){var link=(LinkLabel)x;link.LinkColor=accent;link.ActiveLinkColor=accent;link.VisitedLinkColor=accent;}if(!object.Equals(x.Tag,"colorPreset")&&!object.Equals(x.Tag,"colorSwatch")&&!object.Equals(x.Tag,"brandHeader"))x.BackColor=(x is TabPage||x is GroupBox)?panel:bg;if(x is TextBox||x is NumericUpDown||x is ComboBox){x.BackColor=field;x.ForeColor=fg;}if(x is Button&&!object.Equals(x.Tag,"colorPreset")){var b=(Button)x;b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderSize=1;b.FlatAppearance.BorderColor=dark?Color.FromArgb(91,119,148):Color.FromArgb(112,137,162);if(object.Equals(x.Tag,"primaryAction")){b.BackColor=accent;b.ForeColor=navy;b.FlatAppearance.BorderColor=Color.FromArgb(17,137,174);}else if(object.Equals(x.Tag,"secondaryAction")){b.BackColor=dark?Color.FromArgb(31,55,82):Color.White;b.ForeColor=fg;}}ApplyTheme(x);}}
  void ApplyMenuStyle(){bool dark=IsDark();trayMenu.Font=new Font("Segoe UI",UiFontSize());trayMenu.BackColor=dark?Color.FromArgb(18,35,57):Color.FromArgb(247,251,254);trayMenu.ForeColor=ThemeText();foreach(ToolStripItem i in trayMenu.Items){i.BackColor=trayMenu.BackColor;i.ForeColor=trayMenu.ForeColor;}}
  void Load(){int settingsVersion;using(var k=Registry.CurrentUser.CreateSubKey(@"Software\TrayLiveZoom")){settingsVersion=Convert.ToInt32(k.GetValue("SettingsVersion",1));zoom=Convert.ToInt32(k.GetValue("ZoomPercent",200));speed=Convert.ToInt32(k.GetValue("FollowSpeed",6));animationMs=Convert.ToInt32(k.GetValue("AnimationMs",300));if(settingsVersion<2)animationMs=300;center=Convert.ToInt32(k.GetValue("LockCursorCenter",1))!=0;applyZoomLive=Convert.ToInt32(k.GetValue("ApplyZoomLive",0))!=0;cursorHighlight=Convert.ToInt32(k.GetValue("CursorHighlight",0))!=0;highlightOpacity=Convert.ToInt32(k.GetValue("HighlightOpacity",45));highlightColorArgb=Convert.ToInt32(k.GetValue("HighlightColor",Color.Yellow.ToArgb()));startZoomed=Convert.ToInt32(k.GetValue("StartZoomed",0))!=0;trayClick=Convert.ToInt32(k.GetValue("TrayClick",0))!=0;emergencyEsc=Convert.ToInt32(k.GetValue("EmergencyEsc",1))!=0;hotkeyModifiers=Convert.ToUInt32(k.GetValue("HotkeyModifiers",7));hotkeyKey=Convert.ToUInt32(k.GetValue("HotkeyKey",0x39));fontSizeMode=Convert.ToInt32(k.GetValue("FontSizeMode",1));themeMode=Convert.ToInt32(k.GetValue("ThemeMode",0));languageMode=settingsVersion<8?Localizer.DefaultLanguage():Convert.ToInt32(k.GetValue("LanguageMode",Localizer.DefaultLanguage()));}using(var r=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run")){autostart=r!=null&&(r.GetValue("LumiZoom")!=null||r.GetValue("TrayLiveZoom")!=null);}if(settingsVersion<8){autostart=true;Save();}}
  void Save(){using(var k=Registry.CurrentUser.CreateSubKey(@"Software\TrayLiveZoom")){k.SetValue("ZoomPercent",zoom);k.SetValue("FollowSpeed",speed);k.SetValue("AnimationMs",animationMs);k.SetValue("LockCursorCenter",center?1:0);k.SetValue("ApplyZoomLive",applyZoomLive?1:0);k.SetValue("CursorHighlight",cursorHighlight?1:0);k.SetValue("HighlightOpacity",highlightOpacity);k.SetValue("HighlightColor",highlightColorArgb);k.SetValue("StartZoomed",startZoomed?1:0);k.SetValue("TrayClick",trayClick?1:0);k.SetValue("EmergencyEsc",emergencyEsc?1:0);k.SetValue("HotkeyModifiers",(int)hotkeyModifiers);k.SetValue("HotkeyKey",(int)hotkeyKey);k.SetValue("FontSizeMode",fontSizeMode);k.SetValue("ThemeMode",themeMode);k.SetValue("LanguageMode",languageMode);k.SetValue("SettingsVersion",8);}using(var r=Registry.CurrentUser.CreateSubKey(@"Software\Microsoft\Windows\CurrentVersion\Run")){r.DeleteValue("TrayLiveZoom",false);if(autostart)r.SetValue("LumiZoom","\""+Application.ExecutablePath+"\"");else r.DeleteValue("LumiZoom",false);}}
  void ExitApp(){Native.MagSetFullscreenTransform(1,0,0);Native.RECT a=new Native.RECT(),b=new Native.RECT();Native.MagSetInputTransform(false,ref a,ref b);Native.UnregisterHotKey(window.Handle,ID);Native.MagUninitialize();tray.Visible=false;halo.Dispose();window.Dispose();ExitThread();}
  }
 static class Localizer
 {
  public static readonly object[] LanguageNames={"English","Polski","Deutsch","Español","Français","Italiano","Português","Українська"};
  static readonly string[][] R={
   new[]{"LumiZoom — ustawienia","LumiZoom — Settings","LumiZoom — ustawienia","LumiZoom — Einstellungen","LumiZoom — Configuración","LumiZoom — Paramètres","LumiZoom — Impostazioni","LumiZoom — Definições","LumiZoom — Налаштування"},
   new[]{"Główna","Main","Główna","Hauptseite","Principal","Principal","Principale","Principal","Головна"},
   new[]{"Kursor","Cursor","Kursor","Cursor","Cursor","Curseur","Cursore","Cursor","Курсор"},
   new[]{"Program","Program","Program","Programm","Programa","Programme","Programma","Programa","Програма"},
   new[]{"Wygląd","Appearance","Wygląd","Darstellung","Apariencia","Apparence","Aspetto","Aspeto","Вигляд"},
   new[]{"Poziom powiększenia","Magnification level","Poziom powiększenia","Vergrößerung","Nivel de ampliación","Niveau de zoom","Livello di ingrandimento","Nível de ampliação","Рівень збільшення"},
   new[]{"Zastosuj zmiany powiększenia na żywo","Apply magnification changes instantly","Zastosuj zmiany powiększenia na żywo","Änderungen sofort anwenden","Aplicar cambios al instante","Appliquer les changements instantanément","Applica le modifiche subito","Aplicar alterações imediatamente","Застосовувати зміни одразу"},
   new[]{"Po zaznaczeniu zmiany suwaka i ustawień są od razu widoczne na ekranie.","When enabled, slider and setting changes are immediately visible.","Po zaznaczeniu zmiany suwaka i ustawień są od razu widoczne na ekranie.","Änderungen werden sofort auf dem Bildschirm sichtbar.","Los cambios se muestran inmediatamente en pantalla.","Les modifications sont visibles immédiatement à l’écran.","Le modifiche sono visibili immediatamente sullo schermo.","As alterações ficam imediatamente visíveis no ecrã.","Зміни одразу відображаються на екрані."},
   new[]{"Czas animacji","Animation time","Czas animacji","Animationsdauer","Duración de animación","Durée de l’animation","Durata animazione","Duração da animação","Тривалість анімації"},
   new[]{"Utrzymuj kursor na środku ekranu","Keep cursor in the centre of the screen","Utrzymuj kursor na środku ekranu","Cursor in der Bildschirmmitte halten","Mantener el cursor en el centro","Garder le curseur au centre","Mantieni il cursore al centro","Manter o cursor no centro","Утримувати курсор у центрі"},
   new[]{"Szybkość płynnego śledzenia","Smooth tracking speed","Szybkość płynnego śledzenia","Geschwindigkeit der Nachführung","Velocidad de seguimiento","Vitesse de suivi","Velocità di inseguimento","Velocidade de seguimento","Швидкість стеження"},
   new[]{"Skrót włącz/wyłącz","Zoom on/off shortcut","Skrót włącz/wyłącz","Tastenkürzel Ein/Aus","Atajo activar/desactivar","Raccourci marche/arrêt","Scorciatoia attiva/disattiva","Atalho ligar/desligar","Комбінація увімк./вимк."},
   new[]{"Język aplikacji","Application language","Język aplikacji","Anwendungssprache","Idioma de la aplicación","Langue de l’application","Lingua dell’applicazione","Idioma da aplicação","Мова програми"},
   new[]{"Podświetlaj położenie kursora","Highlight cursor position","Podświetlaj położenie kursora","Cursorposition hervorheben","Resaltar la posición del cursor","Mettre en évidence le curseur","Evidenzia la posizione del cursore","Realçar a posição do cursor","Підсвічувати положення курсора"},
   new[]{"Wybrany kolor","Selected colour","Wybrany kolor","Ausgewählte Farbe","Color seleccionado","Couleur sélectionnée","Colore selezionato","Cor selecionada","Вибраний колір"},
   new[]{"Inny kolor…","Other colour…","Inny kolor…","Andere Farbe…","Otro color…","Autre couleur…","Altro colore…","Outra cor…","Інший колір…"},
   new[]{"Przezroczystość podświetlenia","Highlight opacity","Przezroczystość podświetlenia","Transparenz der Hervorhebung","Opacidad del resaltado","Opacité de la surbrillance","Opacità evidenziazione","Opacidade do realce","Прозорість підсвічування"},
   new[]{"Uruchamiaj razem z Windows","Start with Windows","Uruchamiaj razem z Windows","Mit Windows starten","Iniciar con Windows","Démarrer avec Windows","Avvia con Windows","Iniciar com o Windows","Запускати разом із Windows"},
   new[]{"Włącz powiększenie po uruchomieniu","Enable magnification after startup","Włącz powiększenie po uruchomieniu","Vergrößerung nach Start aktivieren","Activar ampliación al iniciar","Activer le zoom au démarrage","Attiva ingrandimento all’avvio","Ativar ampliação ao iniciar","Увімкнути збільшення після запуску"},
   new[]{"Lewy klik ikony w zasobniku przełącza zoom","Left-click tray icon toggles zoom","Lewy klik ikony w zasobniku przełącza zoom","Linksklick auf Tray-Symbol schaltet Zoom","Clic izquierdo en el icono alterna el zoom","Un clic gauche sur l’icône active le zoom","Clic sinistro sull’icona attiva lo zoom","Clique esquerdo no ícone alterna o zoom","Лівий клік по значку перемикає збільшення"},
   new[]{"Awaryjne wyłączenie klawiszem Esc","Emergency exit with Esc","Awaryjne wyłączenie klawiszem Esc","Not-Aus mit Esc","Salida de emergencia con Esc","Arrêt d’urgence avec Échap","Uscita di emergenza con Esc","Saída de emergência com Esc","Аварійне вимкнення клавішею Esc"},
   new[]{"Rozmiar interfejsu","Interface size","Rozmiar interfejsu","Oberflächengröße","Tamaño de interfaz","Taille de l’interface","Dimensione interfaccia","Tamanho da interface","Розмір інтерфейсу"},
   new[]{"Motyw kolorystyczny","Colour theme","Motyw kolorystyczny","Farbschema","Tema de color","Thème de couleurs","Tema colore","Tema de cores","Колірна тема"},
   new[]{"Podgląd zmienia się natychmiast.","Preview updates instantly.","Podgląd zmienia się natychmiast.","Vorschau wird sofort aktualisiert.","La vista previa se actualiza al instante.","L’aperçu se met à jour instantanément.","L’anteprima si aggiorna subito.","A pré-visualização atualiza-se imediatamente.","Попередній перегляд змінюється одразу."},
   new[]{"Przywróć domyślne","Restore defaults","Przywróć domyślne","Standardwerte","Restaurar valores","Valeurs par défaut","Ripristina predefiniti","Repor predefinições","Відновити типові"},
   new[]{"Wyjdź","Exit","Wyjdź","Beenden","Salir","Quitter","Esci","Sair","Вийти"},
   new[]{"Zapisz i wyjdź","Save and exit","Zapisz i wyjdź","Speichern und beenden","Guardar y salir","Enregistrer et quitter","Salva ed esci","Guardar e sair","Зберегти й вийти"},
   new[]{"Włącz / wyłącz","Enable / disable","Włącz / wyłącz","Ein / Aus","Activar / desactivar","Activer / désactiver","Attiva / disattiva","Ativar / desativar","Увімкнути / вимкнути"},
   new[]{"Opcje...","Settings...","Opcje...","Einstellungen...","Configuración...","Paramètres...","Impostazioni...","Definições...","Налаштування..."},
   new[]{"Zamknij","Close","Zamknij","Schließen","Cerrar","Fermer","Chiudi","Fechar","Закрити"},
   new[]{"aktywny","active","aktywny","aktiv","activo","actif","attivo","ativo","активний"},
   new[]{"wyłączony","disabled","wyłączony","deaktiviert","desactivado","désactivé","disattivato","desativado","вимкнено"},
   new[]{"Wybrany skrót jest zajęty.","The selected shortcut is already in use.","Wybrany skrót jest zajęty.","Das Tastenkürzel wird bereits verwendet.","El atajo seleccionado ya está en uso.","Le raccourci sélectionné est déjà utilisé.","La scorciatoia selezionata è già in uso.","O atalho selecionado já está em uso.","Вибрана комбінація вже використовується."},
   new[]{"Ten skrót jest już używany. Zachowano poprzedni.","This shortcut is already in use. The previous one was kept.","Ten skrót jest już używany. Zachowano poprzedni.","Dieses Tastenkürzel ist belegt. Das vorherige wurde beibehalten.","Este atajo ya está en uso. Se conservó el anterior.","Ce raccourci est déjà utilisé. L’ancien a été conservé.","Questa scorciatoia è già in uso. È stata mantenuta la precedente.","Este atalho já está em uso. O anterior foi mantido.","Ця комбінація вже використовується. Попередню збережено."}
   ,new[]{"O LumiZoom","About LumiZoom","O LumiZoom","Über LumiZoom","Acerca de LumiZoom","À propos de LumiZoom","Informazioni su LumiZoom","Sobre o LumiZoom","Про LumiZoom"}
   ,new[]{"Wersja","Version","Wersja","Version","Versión","Version","Versione","Versão","Версія"}
   ,new[]{"Autor","Author","Autor","Autor","Autor","Auteur","Autore","Autor","Автор"}
   ,new[]{"Bezpłatna lupa ekranowa dla osób niedowidzących.","Free screen magnifier for people with low vision.","Bezpłatna lupa ekranowa dla osób niedowidzących.","Kostenlose Bildschirmlupe für Menschen mit Sehschwäche.","Lupa de pantalla gratuita para personas con baja visión.","Loupe d’écran gratuite pour les personnes malvoyantes.","Lente d’ingrandimento gratuita per persone ipovedenti.","Lupa de ecrã gratuita para pessoas com baixa visão.","Безкоштовна екранна лупа для людей зі слабким зором."}
   ,new[]{"Strona projektu","Project website","Strona projektu","Projektseite","Sitio web del proyecto","Site du projet","Sito del progetto","Site do projeto","Сайт проєкту"}
   ,new[]{"Kontakt","Contact","Kontakt","Kontakt","Contacto","Contact","Contatti","Contacto","Контакт"}
  };
  public static int DefaultLanguage(){string n=System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;return n=="pl"?1:n=="de"?2:n=="es"?3:n=="fr"?4:n=="it"?5:n=="pt"?6:n=="uk"?7:0;}
  static string[] Find(string key){foreach(var r in R)if(r[0]==key)return r;return null;}
  public static string Get(string key,int lang){var r=Find(key);return r==null?key:r[Math.Max(0,Math.Min(7,lang))+1];}
  public static void Apply(Control root,int lang){string key=null;if(root.Name!=null&&root.Name.StartsWith("i18n|"))key=root.Name.Substring(5);else if(Find(root.Text)!=null){key=root.Text;root.Name="i18n|"+key;}if(key!=null)root.Text=Get(key,lang);foreach(Control c in root.Controls)Apply(c,lang);}
 }
 sealed class LanguageCombo:ComboBox
 {
  public LanguageCombo(){DrawMode=DrawMode.OwnerDrawFixed;ItemHeight=30;}
  protected override void OnDrawItem(DrawItemEventArgs e){if(e.Index<0)return;e.DrawBackground();Rectangle flag=new Rectangle(e.Bounds.Left+8,e.Bounds.Top+6,34,18);DrawFlag(e.Graphics,flag,e.Index);using(var p=new Pen(Color.FromArgb(100,120,140)))e.Graphics.DrawRectangle(p,flag);Color text=(e.State&DrawItemState.Selected)!=0?SystemColors.HighlightText:ForeColor;TextRenderer.DrawText(e.Graphics,Items[e.Index].ToString(),Font,new Rectangle(flag.Right+12,e.Bounds.Top,e.Bounds.Width-58,e.Bounds.Height),text,TextFormatFlags.Left|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis);e.DrawFocusRectangle();}
  static void Fill(Graphics g,Brush b,Rectangle r){g.FillRectangle(b,r);}static void DrawFlag(Graphics g,Rectangle r,int i){using(var white=new SolidBrush(Color.White))using(var red=new SolidBrush(Color.FromArgb(210,32,48)))using(var blue=new SolidBrush(Color.FromArgb(24,72,150)))using(var yellow=new SolidBrush(Color.FromArgb(255,205,35)))using(var black=new SolidBrush(Color.FromArgb(28,28,28)))using(var green=new SolidBrush(Color.FromArgb(24,145,74))){Fill(g,white,r);int h=r.Height/3,w=r.Width/3;if(i==0){Fill(g,blue,r);g.FillRectangle(white,r.X+r.Width/2-3,r.Y,6,r.Height);g.FillRectangle(white,r.X,r.Y+r.Height/2-3,r.Width,6);g.FillRectangle(red,r.X+r.Width/2-2,r.Y,4,r.Height);g.FillRectangle(red,r.X,r.Y+r.Height/2-2,r.Width,4);}else if(i==1){Fill(g,red,new Rectangle(r.X,r.Y+r.Height/2,r.Width,r.Height-r.Height/2));}else if(i==2){Fill(g,black,new Rectangle(r.X,r.Y,r.Width,h));Fill(g,red,new Rectangle(r.X,r.Y+h,r.Width,h));Fill(g,yellow,new Rectangle(r.X,r.Y+2*h,r.Width,r.Height-2*h));}else if(i==3){Fill(g,red,r);Fill(g,yellow,new Rectangle(r.X,r.Y+h,r.Width,r.Height-2*h));}else if(i==4){Fill(g,blue,new Rectangle(r.X,r.Y,w,r.Height));Fill(g,red,new Rectangle(r.X+2*w,r.Y,r.Width-2*w,r.Height));}else if(i==5){Fill(g,green,new Rectangle(r.X,r.Y,w,r.Height));Fill(g,red,new Rectangle(r.X+2*w,r.Y,r.Width-2*w,r.Height));}else if(i==6){Fill(g,green,new Rectangle(r.X,r.Y,(int)(r.Width*.42),r.Height));Fill(g,red,new Rectangle(r.X+(int)(r.Width*.42),r.Y,r.Width-(int)(r.Width*.42),r.Height));}else if(i==7){Fill(g,blue,new Rectangle(r.X,r.Y,r.Width,r.Height/2));Fill(g,yellow,new Rectangle(r.X,r.Y+r.Height/2,r.Width,r.Height-r.Height/2));}}}
 }
 sealed class BrandHeader:Control
 {
  public bool Dark;
  public BrandHeader(){SetStyle(ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer|ControlStyles.UserPaint|ControlStyles.SupportsTransparentBackColor,true);BackColor=Color.Transparent;}
  protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);var g=e.Graphics;g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;float d=Math.Min(46,Height-4),x=2,y=(Height-d)/2f;using(var hp=new Pen(Color.FromArgb(10,28,57),Math.Max(4,d*.15f)))g.DrawLine(hp,x+d*.72f,y+d*.72f,x+d*1.03f,y+d*1.03f);using(var rim=new SolidBrush(Color.FromArgb(24,48,79)))g.FillEllipse(rim,x,y,d,d);using(var lens=new SolidBrush(Color.FromArgb(33,181,224)))g.FillEllipse(lens,x+d*.13f,y+d*.13f,d*.74f,d*.74f);using(var white=new SolidBrush(Color.White)){g.FillRectangle(white,x+d*.34f,y+d*.26f,d*.13f,d*.47f);g.FillRectangle(white,x+d*.34f,y+d*.61f,d*.34f,d*.13f);g.FillEllipse(white,x+d*.64f,y+d*.25f,d*.10f,d*.10f);}Color text=Dark?Color.FromArgb(245,250,255):Color.FromArgb(15,39,70);TextRenderer.DrawText(g,"LumiZoom",Font,new Rectangle((int)(x+d+18),0,Width-(int)(x+d+18),Height),text,TextFormatFlags.Left|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPadding|TextFormatFlags.EndEllipsis);}
 }
 sealed class StyledTabControl:TabControl{public bool Dark;public StyledTabControl(){DrawMode=TabDrawMode.OwnerDrawFixed;SizeMode=TabSizeMode.Fixed;SetStyle(ControlStyles.OptimizedDoubleBuffer,true);}public void UpdateTabWidths(){if(TabCount>0){Size wanted=new Size(Math.Max(80,(Width-8)/TabCount),Math.Max(34,(int)(Font.Size*2.25f)));if(ItemSize!=wanted)ItemSize=wanted;}Invalidate();}protected override void OnDrawItem(DrawItemEventArgs e){bool selected=e.Index==SelectedIndex;Rectangle r=GetTabRect(e.Index);Color bg=Dark?(selected?Color.FromArgb(30,58,86):Color.FromArgb(14,27,46)):(selected?Color.White:Color.FromArgb(224,236,245));Color fg=Dark?Color.FromArgb(244,249,255):Color.FromArgb(15,39,70);using(var b=new SolidBrush(bg))e.Graphics.FillRectangle(b,r);TextRenderer.DrawText(e.Graphics,TabPages[e.Index].Text,Font,r,fg,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.EndEllipsis);if(selected)using(var b=new SolidBrush(Color.FromArgb(31,181,224)))e.Graphics.FillRectangle(b,r.Left,r.Bottom-5,r.Width,5);}}
 sealed class CursorHalo:Form{Color color=Color.Yellow;public CursorHalo(){FormBorderStyle=FormBorderStyle.None;ShowInTaskbar=false;TopMost=true;Width=70;Height=70;BackColor=Color.Black;TransparencyKey=Color.Black;StartPosition=FormStartPosition.Manual;}protected override bool ShowWithoutActivation{get{return true;}}protected override CreateParams CreateParams{get{var p=base.CreateParams;p.ExStyle|=0x20|0x80|0x80000;return p;}}public void SetAppearance(Color c,int opacity){color=c;Opacity=Math.Max(.1,Math.Min(1,opacity/100.0));Invalidate();}public void ShowAt(int x,int y){Location=new Point(x-Width/2,y-Height/2);if(!Visible)Show();}protected override void OnPaint(PaintEventArgs e){e.Graphics.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using(var p=new Pen(color,7))e.Graphics.DrawEllipse(p,7,7,Width-15,Height-15);}}
 sealed class MessageWindow:NativeWindow,IDisposable{public event Action HotkeyPressed;public MessageWindow(){CreateHandle(new CreateParams());}protected override void WndProc(ref Message m){if(m.Msg==0x0312&&HotkeyPressed!=null)HotkeyPressed();base.WndProc(ref m);}public void Dispose(){DestroyHandle();}}
 static class Native{
  [StructLayout(LayoutKind.Sequential)]public struct POINT{public int X,Y;} [StructLayout(LayoutKind.Sequential)]public struct RECT{public int Left,Top,Right,Bottom;}
  [DllImport("Magnification.dll")]public static extern bool MagInitialize();[DllImport("Magnification.dll")]public static extern bool MagUninitialize();[DllImport("Magnification.dll")]public static extern bool MagSetFullscreenTransform(float l,int x,int y);[DllImport("Magnification.dll",SetLastError=true)]public static extern bool MagSetInputTransform(bool e,ref RECT s,ref RECT d);
  [DllImport("user32.dll")]public static extern bool RegisterHotKey(IntPtr h,int id,uint m,uint k);[DllImport("user32.dll")]public static extern bool UnregisterHotKey(IntPtr h,int id);[DllImport("user32.dll")]public static extern int GetSystemMetrics(int i);[DllImport("user32.dll")]public static extern bool GetCursorPos(out POINT p);
  [DllImport("user32.dll",CharSet=CharSet.Unicode)]public static extern IntPtr SendMessage(IntPtr h,int msg,IntPtr w,string text);
 }
}
